packages:
  - packages/*
catalog:
  ghost: 6.0.7
  juice: ^11.0.0
  cheerio: ^1.0.0
  clsx: ^2.1.1
  "@tryghost/color-utils": "^0.2.10"
configDependencies:
  ghost: "6.0.5+sha512-68jiWSufTHqlqi8cQ27jcS5fAhppVhZhwM3KffI5zqu7ZG74HBkY5bksN+Ii067DX/ZaMYUaFtvsHse4jK41NA=="
ignoredBuiltDependencies:
  - sqlite3
onlyBuiltDependencies:
  - esbuild
overrides:
  "@tryghost/i18n": "file:./node_modules/.pnpm-config/ghost/components/tryghost-i18n-6.0.5.tgz"
  # override juice and cheerio
  # MAKE SURE API CHANGES ARE NOT BREAKING:
  # - https://github.com/Automattic/juice/releases
  # - https://github.com/cheeriojs/cheerio/releases
  "@tryghost/kg-default-cards>juice@^10.0.0": "catalog:"
  ghost>juice@9.1.0: "catalog:"
  ghost>cheerio@0.22.0: "catalog:"
  "@tryghost/url-utils>cheerio@^0.22.0": "catalog:"
  "@tryghost/i18n>i18next": "-"
  ghost>@extractus/oembed-extractor: "-"
  ghost>@faker-js/faker: "-"
  ghost>@isaacs/ttlcache: "-"
  ghost>@sentry/node: "-"
  ghost>@slack/webhook: "-"
  ghost>@tryghost/adapter-base-cache: "-"
  ghost>@tryghost/admin-api-schema: "-"
  ghost>@tryghost/api-framework: "-"
  ghost>@tryghost/bookshelf-plugins: "-"
  ghost>@tryghost/config-url-helpers: "-"
  ghost>@tryghost/custom-fonts: "-"
  ghost>@tryghost/database-info: "-"
  ghost>@tryghost/debug: "-"
  ghost>@tryghost/domain-events: "-"
  ghost>@tryghost/email-mock-receiver: "-"
  ghost>@tryghost/errors: "-"
  ghost>@tryghost/helpers: "-"
  ghost>@tryghost/http-cache-utils: "-"
  ghost>@tryghost/i18n: "-"
  ghost>@tryghost/image-transform: "-"
  ghost>@tryghost/job-manager: "-"
  # ghost>@tryghost/kg-card-factory: "-"
  ghost>@tryghost/kg-converters: "-"
  ghost>@tryghost/kg-default-atoms: "-"
  ghost>@tryghost/kg-default-nodes: "-"
  ghost>@tryghost/kg-html-to-lexical: "-"
  # ghost>@tryghost/kg-mobiledoc-html-renderer: "-"
  ghost>@tryghost/limit-service: "-"
  ghost>@tryghost/logging: "-"
  ghost>@tryghost/members-csv: "-"
  ghost>@tryghost/metrics: "-"
  ghost>@tryghost/mw-error-handler: "-"
  ghost>@tryghost/mw-vhost: "-"
  # ghost>@tryghost/nodemailer: "-"
  ghost>@tryghost/nql: "-"
  ghost>@tryghost/pretty-cli: "-"
  ghost>@tryghost/prometheus-metrics: "-"
  ghost>@tryghost/promise: "-"
  ghost>@tryghost/referrer-parser: "-"
  ghost>@tryghost/request: "-"
  ghost>@tryghost/root-utils: "-"
  ghost>@tryghost/security: "-"
  ghost>@tryghost/social-urls: "-"
  ghost>@tryghost/string: "-"
  ghost>@tryghost/tpl: "-"
  ghost>@tryghost/url-utils: "-"
  ghost>@tryghost/validator: "-"
  ghost>@tryghost/version: "-"
  ghost>@tryghost/zip: "-"
  ghost>amperize: "-"
  ghost>body-parser: "-"
  ghost>bookshelf: "-"
  ghost>bookshelf-relations: "-"
  ghost>brute-knex: "-"
  ghost>bson-objectid: "-"
  ghost>cache-manager: "-"
  ghost>cache-manager-ioredis: "-"
  ghost>chalk: "-"
  ghost>charset: "-"
  ghost>cluster-key-slot: "-"
  ghost>common-tags: "-"
  ghost>compression: "-"
  ghost>connect-slashes: "-"
  ghost>cookie-session: "-"
  ghost>cookies: "-"
  ghost>cors: "-"
  ghost>countries-and-timezones: "-"
  ghost>csso: "-"
  ghost>csv-writer: "-"
  ghost>date-fns: "-"
  ghost>dompurify: "-"
  ghost>downsize: "-"
  ghost>express: "-"
  ghost>express-brute: "-"
  ghost>express-hbs: "-"
  ghost>express-jwt: "-"
  ghost>express-lazy-router: "-"
  ghost>express-query-boolean: "-"
  ghost>express-queue: "-"
  ghost>express-session: "-"
  ghost>file-type: "-"
  ghost>form-data: "-"
  ghost>fs-extra: "-"
  ghost>ghost-storage-base: "-"
  ghost>glob: "-"
  ghost>got: "-"
  ghost>gscan: "-"
  ghost>html-to-text: "-"
  ghost>human-number: "-"
  ghost>iconv-lite: "-"
  ghost>image-size: "-"
  ghost>intl: "-"
  ghost>intl-messageformat: "-"
  ghost>js-yaml: "-"
  ghost>json-stable-stringify: "-"
  ghost>jsonc-parser: "-"
  ghost>jsonpath: "-"
  ghost>jsonwebtoken: "-"
  ghost>keypair: "-"
  ghost>knex: "-"
  ghost>knex-migrator: "-"
  ghost>leaky-bucket: "-"
  ghost>lodash: "-"
  ghost>luxon: "-"
  ghost>mailgun.js: "-"
  ghost>metascraper: "-"
  ghost>metascraper-author: "-"
  ghost>metascraper-description: "-"
  ghost>metascraper-image: "-"
  ghost>metascraper-logo: "-"
  ghost>metascraper-logo-favicon: "-"
  ghost>metascraper-publisher: "-"
  ghost>metascraper-title: "-"
  ghost>metascraper-url: "-"
  ghost>mime-types: "-"
  ghost>moment: "-"
  ghost>moment-timezone: "-"
  ghost>multer: "-"
  ghost>mysql2: "-"
  ghost>nconf: "-"
  ghost>node-fetch: "-"
  ghost>node-jose: "-"
  ghost>nodemailer: "-"
  ghost>otplib: "-"
  ghost>papaparse: "-"
  ghost>path-match: "-"
  ghost>probability-distributions: "-"
  ghost>probe-image-size: "-"
  ghost>rss: "-"
  ghost>sanitize-html: "-"
  ghost>semver: "-"
  ghost>simple-dom: "-"
  ghost>stoppable: "-"
  ghost>stripe: "-"
  ghost>superagent: "-"
  ghost>superagent-throttle: "-"
  ghost>terser: "-"
  ghost>tiny-glob: "-"
  ghost>tough-cookie: "-"
  ghost>ua-parser-js: "-"
  ghost>uuid: "-"
  ghost>xml: "-"
patchedDependencies:
  ghost: patches/ghost.patch
  "@tryghost/html-to-plaintext": patches/@tryghost__html-to-plaintext.patch
  "@changesets/assemble-release-plan": patches/@changesets__assemble-release-plan.patch
